language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install nose coverage flake8
  - python setup.py develop --quiet
script:
  - flake8 rudolf.py --ignore=E501,E128,E701,E261,E301,E126,E12
  - coverage run --source rudolf -m nose 
  - coverage report
